# -*- coding: utf-8 -*-
"""image_preprocessing_and_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Ix--gHNH6b1OiFUlJsKT8chQmwPKI81

###Intro
This project explores foundational deep learning and image preprocessing workflows across three related tasks. It begins with building a neural network for Fashion-MNIST classification, then moves into image loading and augmentation with the TensorFlow flower dataset, and finishes with OpenCV-based preprocessing and visualization for computer vision pipelines.

**Part 1- Neural Network**
"""

import numpy as np
import os
import PIL
import PIL.Image
import tensorflow as tf
import tensorflow_datasets as tfds
import pathlib
import matplotlib.pyplot as plt
import keras.datasets.fashion_mnist as fashion_mnist

# Download and extract the flower dataset, auto-create subfolders
dataset_url = "https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz"
data_dir = tf.keras.utils.get_file(origin=dataset_url, fname='flower_photos', untar=True)
data_dir = pathlib.Path(data_dir)

(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

# plot 4 images as gray scale
plt.figure(figsize=(10,10))
for i in range(16):
    plt.subplot(4,4,i+1)
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)
    plt.imshow(X_train[i], cmap=plt.cm.binary)
    plt.xlabel(class_names[y_train[i]])
plt.show()

# flatten 28*28 images to a 784 vector for each image
IMG_HEIGHT=28
IMG_WIDTH= 28
channels =1

# normalize inputs from 0-255 to 0-1
X_train = X_train / 255
X_test = X_test / 255

#Create model
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False)
model = tf.keras.Sequential([
                             tf.keras.layers.Flatten(input_shape=(IMG_HEIGHT, IMG_WIDTH)),
                             tf.keras.layers.Dense(128, activation= 'relu'),
                             tf.keras.layers.Dense(10, activation= 'softmax')])
model.compile(optimizer='adam', loss= loss_fn, metrics=['accuracy'])

# Train model
hist = model.fit(X_train, y_train, validation_split=0.2, epochs=20, batch_size=128)

plt.subplot(2,1,1)
plt.plot(hist.history['accuracy'])
plt.plot(hist.history['val_accuracy'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='lower right')

plt.subplot(2,1,2)
plt.plot(hist.history['loss'])
plt.plot(hist.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper right')

plt.tight_layout()
plt.show()

"""### Analysis for Part 1

The neural network trained on the Fashion-MNIST dataset using a single hidden layer with 128 ReLU units achieved strong results within 20 epochs. The learning curves for accuracy and loss show that both training and validation performance improved rapidly in the first few epochs, then gradually leveled off as the model converged. By epoch 20, the training accuracy reached about 92% and the validation accuracy reached around 91%, indicating that the model generalizes well to new data. The gap between the training and validation curves is minimal, suggesting that overfitting is not a significant issue in this architecture.

The loss curves decrease steadily for both training and validation sets, further indicating consistent and stable learning. The final validation loss stabilizes at a low value that is close to the training loss, which is another good sign that the model is not significantly overfitting.

Suggestions for Improvement:

As an experiment, deeper architectures (adding more hidden layers or increasing the number of nodes) could be tested to see if performance further improves.

Regularization methods such as dropout could be introduced if overfitting is observed with a larger or more complex model.

Early stopping or increasing the number of epochs may help optimize learning if validation accuracy plateaus prior to the 20th epoch.

**Part 2- Image Processing**

Load the Flower photo dataset from tensorflow repository
"""

dataset_url = "https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz"
data_dir = tf.keras.utils.get_file(origin=dataset_url,
                                   fname='flower_photos',
                                   untar=True)
data_dir = pathlib.Path(data_dir)

image_count = len(list(data_dir.glob('*/*.jpg')))  #This will count all the file with extension of jpg
print(image_count)

"""* The list of subfolders are:*
*   daisy
*   dandelion
*   roses
*   sunflowers
*   tulips

We can look into any of the subfolders to see images stored. Look into the folder using: data_dir.glob('tulips/*')


Use Pillow (PIL) to show flower from each subfolder

"""

from PIL import Image
#tulips = list(tulips_dir.glob('*.jpg'))    #This line stores the list of data in subfolder
#PIL.Image.open(str(tulips[2]))              # Use Pillow here to plot the image

# Reference the subfolder within the nested flower_photos
base_dir = pathlib.Path('/root/.keras/datasets/flower_photos/flower_photos')
tulips_dir = base_dir / "tulips"
tulips = list(tulips_dir.glob('*.jpg'))

print(f"Found {len(tulips)} tulip images.")

if len(tulips) > 0:
    img = Image.open(str(tulips[0]))
    plt.imshow(img)
    plt.axis('off')
    plt.show()
else:
    print("No tulip images found. Check your dataset and path.")

print(data_dir)  # Check the path
print(list(data_dir.iterdir()))  # List subfolders

"""* Use Keras to resize all the images into same dimension 180x180"""

batch_size = 32
img_height = 180
img_width = 180

# Convert all the images in data_dir folder into 180x180 using tf.kera.utils.image_dataset_from_directory
# Modify following code
data_dir = pathlib.Path('/root/.keras/datasets/flower_photos/flower_photos')
train_ds = tf.keras.utils.image_dataset_from_directory(
    data_dir,                  # Path to main folder containing subfolders of images
    validation_split=0.2,      # Set aside 20% for validation
    subset="training",         # This dataset is for training
    seed=123,                  # Seed for shuffling and split reproducibility
    image_size=(180, 180),     # Resize images to 180x180
    batch_size=32              # Batch size (can be set as required)
    )

# Use the same strategy to create validation data, this time from validation subset
val_ds = tf.keras.utils.image_dataset_from_directory(
    data_dir,
    validation_split=0.2,
    subset="validation",
    seed=123,
    image_size=(180, 180),
    batch_size=32
)

"""* Use `train_ds.class_names` command to get the list of labels.

* Below we Randomly show 9 images from training data while printing their label on top of the image.
"""

class_names = train_ds.class_names
plt.figure(figsize=(10, 10))
for images, labels in train_ds.take(1):
  for i in range(9):
    ax = plt.subplot(3, 3, i + 1)
    plt.imshow(images[i].numpy().astype("uint8"))
    plt.title(class_names[labels[i]])
    plt.axis("off")

# Some barriers in images for having a proper classification are....

 # Background clutter, varying lighting conditions, occlusions, and similarity in color and shape between different categories

""" * Now, we want to use preprocessing package in Keras to apply different filters to the image. Appllied the following procedures to image data:
- *Rescale the image by dividing by 255*
- *Shear the image 20%*
- *Zoom the image 20%*
- *Horizontally flip the images*
"""

from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(
    rescale=1./255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True
    )

training_set = train_datagen.flow_from_directory(
    data_dir,
    target_size=(180, 180),
    batch_size=batch_size,
    class_mode='categorical'
)

images, labels = next(training_set)

plt.figure(figsize=(10, 10))
for i in range(9):
    ax = plt.subplot(3, 3, i + 1)
    # Force a horizontal flip for demonstration
    flipped_img = np.fliplr(images[i])
    plt.imshow(flipped_img)
    plt.axis("off")
plt.show()

"""###Analysis for Part 2

The flower dataset contains images from five different flower classes, but there are several practical barriers affecting classification performance. Firstly, there is a large variation in backgrounds: some images include sky or foliage, while others feature objects or people, introducing noise irrelevant to the flower itself. In addition, the images vary in brightness, color, and composition, with flowers sometimes occluded, off-center, or surrounded by other plant parts. This intra-class diversity (differences in appearance within the same class) and inter-class similarity (visual resemblance between flowers of different classes) can make it challenging for a model to consistently learn discriminative features.

Further, there are discrepancies in image resolutions and scales—some flowers are close-up while others are in clusters or far away—causing the model to struggle with extracting consistent spatial features. Preprocessing steps such as resizing and augmenting (rescale, shear, zoom, horizontal flip) address some variability but may also introduce new challenges, such as loss of resolution or distortion. To improve model robustness, further augmentation (random cropping, color jittering) and careful curation to balance the dataset and reduce background clutter could be incorporated.

**Part 3- OPENCV**- Now use opencv for preprocessing. Show first 9 images in dataset using Opencv. Before showing each image, resize the images to 180x180.
"""

# Repeat same preprocessing but this time using OpenCV. Show first 9 images in dataset using Opencv.
# Before showing each image, resize the images to 180x180.
import cv2
import pathlib
list_of_images= list(data_dir.glob('*/*.jpg'))
class_names = train_ds.class_names
plt.figure(figsize=(10, 10))
fig=plt.figure(figsize=(16, 12))

for i in range(9):
    # Add appropriate lines of code to create this output
    img_path = str(list_of_images[i])
    img = cv2.imread(img_path)
    resized_img = cv2.resize(img, (180, 180))
    # Convert BGR (OpenCV default) to RGB for matplotlib
    RGB_img = cv2.cvtColor(resized_img, cv2.COLOR_BGR2RGB)
    plt.subplot(3, 3, i + 1)
    plt.imshow(RGB_img)
    plt.title(class_names[i % len(class_names)])
    plt.axis('off')
plt.tight_layout()
plt.show()

"""OpenCV uses BGR as its default colour order for images, matplotlib uses RGB. When you display an image loaded with OpenCv in matplotlib the channels will be back to front.
The easiest way of fixing this is to use OpenCV to explicitly convert it back to RGB, much like you do when creating the greyscale image.
`RGB_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)`
"""

image_dir = pathlib.Path('/root/.keras/datasets/flower_photos/flower_photos')
image_list = list(image_dir.glob('*/*.jpg'))  # Recursively find images in subfolders

num_images = min(6, len(image_list))
plt.figure(figsize=(12, 8))
for i in range(num_images):
    img = cv2.imread(str(image_list[i]))
    RGB_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    plt.subplot(2, 3, i+1)
    plt.imshow(RGB_img)
    plt.axis('off')

plt.tight_layout()
plt.show()

""".

.


.

.

.

.........................................




.........................................



.........................................



.........................................
.


....
............
.



........
..........
..


.....
............................................



.....
.......
................................................


.
...............
..


.
.
.
.
.
.
.
.
.
.

###Analysis for Part 3

Preprocessing with OpenCV offers hands-on control over resizing, color correction, and further low-level transformations. Converting images from BGR to RGB enables accurate visualization and compatibility with plotting libraries such as matplotlib. Resizing all images to a uniform size (180x180) is crucial for feeding data into deep learning models, maintaining consistency across the dataset. However, simple resizing can result in distortion if aspect ratios differ, and can cause loss of fine detail, especially in close-up flower images.

This method allows for batch loading and inspection of raw pixel data, but it does not provide higher-level augmentations like those in Keras' ImageDataGenerator. The advantage of OpenCV is in low-level, efficient image operations and visualization for debugging or quality control. A potential downside is the manual setup needed for more complex transformations (e.g., shearing or random flips), which are easier to configure in high-level libraries. To further enhance preprocessing in OpenCV, users can add manual augmentations (flips, rotations) and combine these scripts with Keras pipelines for a comprehensive approach.


....

.

.

.

.

..

.



.

.

.

.

.



.

.

.

.

.

.

.

This is so the Print to PDF function captures all the notebook
"""



"""....

.

.

.


.

.

.

.

.

.



.

.

.

.

.

.
.

.

.

.

.

.

.

.

.

.
.


.
.

.

.

.

.




.

...







.

.

.

.

.
.

.



...






.
.
.
.
.
.
.
.
...

###Conclusion
This project demonstrates how model performance depends not only on architecture, but also on consistent preprocessing and data handling. Across neural network training, Keras-based augmentation, and OpenCV image processing, the work highlights the importance of normalization, resizing, color-space conversion, and dataset preparation in building reliable vision models
"""

