# -*- coding: utf-8 -*-
"""cnn_image_classification_transfer_learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sf3DZkwf1Y4h9fe_S84jPX-8lzo8Esl_

#Introduction
This notbook explored convolutional neural network (CNN) architectures and their application to image classification tasks. We implemented custom built CNNs as well as fine tuned state of the art pre-trained models, analyzing model performance on MNIST (handwritten digits) and CIFAR-10 (object images). Emphasis was placed on proper preprocessing, regularization, augmentation, and transfer learning strategies to maximize accuracy.

##Section Descriptions


##1. Data Preparation and Visualization (MNIST)
Imported MNIST data and visualized samples to confirm the nature of the task.

Reshaped data to fit Keras' expected input dimensions based on the backend format.

Normalized image pixel values from to.​

One-hot encoded the labels for multiclass classification.​

##2. Building and Training a Custom CNN (MNIST)
Designed a CNN with four convolutional layers (two with 32 filters, two with 64 filters), followed by batch normalization and a fully connected layer with 512 nodes.

Compiled with categorical crossentropy loss for multiclass classification.

Trained with batch size 128 and 20 epochs.

Validated on the test set and achieved high accuracy (≈99%).

Plotted learning curves and interpreted model convergence, generalization, and overfitting:​

##3. CIFAR-10 Data Preparation and Visualization
Loaded CIFAR-10 data and checked image shapes.

Visualized random samples to confirm diverse image classes.

One-hot encoded target labels.

##4. CIFAR-10 Custom CNN and Regularization
Applied data augmentation (shear, zoom, horizontal flip) via ImageDataGenerator.

Constructed a deeper CNN (32 and 64 filters, two dense layers: 512 and 256 units).

Trained with augmentation and plotted learning curves.

Noted mild overfitting and applied dropout to mitigate (Dropout layers after convolutions and dense).

Observed regularization effects in improved generalization and more stable validation accuracy.​

##5. Transfer Learning with Pretrained Models
Implemented VGG16 and ResNet50 pre-trained networks for CIFAR-10 classification.

Used appropriate preprocessing (preprocess_input) for each model and ensured raw images were passed in (no manual normalization).

Augmented training images and unfroze last layers to allow fine-tuning on CIFAR-10.

Compared baseline VGG16 and ResNet50 (with all layers frozen) to fine-tuned versions, noting significant accuracy improvement when proper preprocessing and layer-unfreezing were applied.

VGG16 (Fine-tuning)
Achieved >54% accuracy with improved preprocessing and partial layer unfreezing after initial results were stuck near random (10%).

Training and validation accuracy improved through these corrections.​

ResNet50 (Fine-tuning)
Baseline accuracy was poor at 35% due to preprocessing problems and no layer unfreezing.

Accuracy improved upon:

Removing manual normalization (letting preprocess_input handle it)

Unfreezing last 10 layers

Using Adam optimizer with learning rate scheduling and early stopping.​

##6. Learning Curves and Analysis
Provided a utility function to plot training and validation loss and accuracy.

Used plots to diagnose overfitting and underfitting throughout the experiments.
"""

import keras
import tensorflow as tf
from tensorflow.keras.layers import MaxPooling2D
from keras.datasets import mnist, cifar10
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Activation
from keras.layers import Conv2D
from keras.layers import BatchNormalization
import matplotlib.pyplot as plt
from keras.utils import to_categorical
from keras.layers import Dense
from keras import optimizers
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from keras import backend as K

# Create train and test dataset
(X_train, y_train), (X_test, y_test) = mnist.load_data()

"""1.a. start with creating a visualization of your input data"""

#1.a. Create visualization here
# Look into the dataset by visualizing some data points
fig, axs = plt.subplots(1, 6)
for i in range(6):
    axs[i].imshow(X_train[i], cmap='gray')
    axs[i].axis('off')
plt.show()

# Visualize 9 images
for i in range(9):
    plt.subplot(330 + 1 + i)
    plt.imshow(X_train[i], cmap=plt.get_cmap('gray'))
plt.show()

#preprocessing
# Kears allows us to add the number of channels either to the beggining of shape or the end of it
img_rows, img_cols = 28, 28

if K.image_data_format() == 'channels_first':
    X_train = X_train.reshape(X_train.shape[0], 1, img_rows, img_cols)
    X_test = X_test.reshape(X_test.shape[0], 1, img_rows, img_cols)
    input_shape = (1, img_rows, img_cols)
else:
    X_train = X_train.reshape(X_train.shape[0], img_rows, img_cols, 1)
    X_test = X_test.reshape(X_test.shape[0], img_rows, img_cols, 1)
    input_shape = (img_rows, img_cols, 1)

# You need to apply some preprocessing on X and y

# normalize inputs from 0-255 to 0-1
X_train = X_train.astype('float32') / 255
X_test = X_test.astype('float32') / 255

# Encode outputs
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

"""1.b. Create a CNN model with 4 convolution layers in which two of them have 32 and two of them have 64 filters. The fully connected layer has one hidden layer (512 nodes). Draw the Learning curve. What is your understanding from learning curve? Batch size=128 and epochs=20"""

#1.b.
# Create model here
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=input_shape))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(BatchNormalization())
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(BatchNormalization())
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dense(10, activation='softmax'))

print(y_train.shape)  # Should print (num_samples, 10)
print(y_test.shape)   # Should print (num_samples, 10)

model.compile(loss='categorical_crossentropy', optimizer='adam',  metrics=['accuracy'])
hist = model.fit(X_train, y_train, batch_size=128, epochs=20, validation_data=(X_test, y_test), verbose=2) #Start training the model

# Measure test accuracy
scores = model.evaluate(X_test, y_test, verbose=1) #Measure test accuracy
print("Accuracy: %.2f%%" % (scores[1]*100))

# Draw Learning curve
#Create a function to draw learning curves
def learning_curve(hist):
    plt.figure(figsize=(12,4))
    plt.subplot(1,2,1)
    plt.plot(hist.history['loss'], label='Train Loss')
    plt.plot(hist.history['val_loss'], label='Val Loss')
    plt.title('Loss')
    plt.legend()
    plt.subplot(1,2,2)
    plt.plot(hist.history['accuracy'], label='Train Acc')
    plt.plot(hist.history['val_accuracy'], label='Val Acc')
    plt.title('Accuracy')
    plt.legend()
    plt.show()

learning_curve(hist)

## understanding from learning curves -
# They look fine. There is a little bit of overfitting but nothing to be worried about

"""**Part 2- CIFAR10**"""

(X_train, y_train), (X_test, y_test) = cifar10.load_data()# Load CIFAR 10 data here
labels= ["airplane","automobile","bird","cat","deer","dog","frog","horse","ship","truck"]
print(X_train.shape)
print(X_test.shape)

# 2.a. Let's look into the dataset by visualizing some data opints
for i in range(9):
    plt.subplot(330 + 1 + i)
    plt.imshow(X_train[i])
plt.show()

"""2.b. Apply pre-processing algorithms. The augmented images are supposed to be seared by 20%, zoomed by 20% and horizontally flipped. Now, we design a CNN model with 4 convolution layers in which two of them have 32 and two of them have 64 filters. The fully connected layer has two hidden layers (512 and 256 nodes respectively)."""

# 2.b
# Encoding output
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

# Normalize inputs from 0-255 to 0-1
X_train = X_train.astype('float32') / 255
X_test = X_test.astype('float32') / 255
# create data generator
datagen = ImageDataGenerator(
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True)
datagen.fit(X_train)
# prepare iterator
it_train = datagen.flow(X_train, y_train, batch_size=128)

# Create model here
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(32,32,3)))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(BatchNormalization())
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(BatchNormalization())
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(10, activation='softmax'))


model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
hist = model.fit(it_train, epochs=20, validation_data=(X_test, y_test), steps_per_epoch=len(X_train)//128, verbose=2)# start training

# Draw learning curve here
def learning_curve(hist):
    plt.figure(figsize=(12,4))
    plt.subplot(1,2,1)
    plt.plot(hist.history['loss'], label='Train Loss')
    plt.plot(hist.history['val_loss'], label='Val Loss')
    plt.title('Loss')
    plt.legend()
    plt.subplot(1,2,2)
    plt.plot(hist.history['accuracy'], label='Train Acc')
    plt.plot(hist.history['val_accuracy'], label='Val Acc')
    plt.title('Accuracy')
    plt.legend()
    plt.show()
learning_curve(hist)

#2.c. Solution to resolve overfitting
# One solution is adding drop out
# Implement solution below and train model
model_dropout = Sequential()
model_dropout.add(Conv2D(32, (3, 3), activation='relu', input_shape=(32,32,3)))
model_dropout.add(Conv2D(32, (3, 3), activation='relu'))
model_dropout.add(MaxPooling2D(pool_size=(2,2)))
model_dropout.add(BatchNormalization())
model_dropout.add(Dropout(0.25))
model_dropout.add(Conv2D(64, (3, 3), activation='relu'))
model_dropout.add(Conv2D(64, (3, 3), activation='relu'))
model_dropout.add(MaxPooling2D(pool_size=(2,2)))
model_dropout.add(BatchNormalization())
model_dropout.add(Dropout(0.25))
model_dropout.add(Flatten())
model_dropout.add(Dense(512, activation='relu'))
model_dropout.add(Dropout(0.5))
model_dropout.add(Dense(256, activation='relu'))
model_dropout.add(Dense(10, activation='softmax'))

model_dropout.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
hist_dropout = model_dropout.fit(it_train, epochs=20, validation_data=(X_test, y_test), steps_per_epoch=len(X_train)//128, verbose=2)

# Draw learning curve - we can see there is less overfiting so we are happy with solution results
learning_curve(hist_dropout)

# 2.d- This part is experimenting with pre-trained models - VGG16 and RESNet50
# Implementing VGG16
from keras.applications.vgg16 import VGG16
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
from keras.models import Model
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.applications.vgg16 import preprocess_input as vgg_preprocess
from tensorflow.keras.applications.resnet50 import preprocess_input as resnet_preprocess

import numpy as np

# Load data
(X_train, y_train), (X_test, y_test) = cifar10.load_data()
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)
# DO NOT normalize X_train or X_test to float or [0,1].

# Augmentation and VGG preprocessing for training data
datagen = ImageDataGenerator(
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    preprocessing_function=preprocess_input
)
datagen.fit(X_train)
train_flow = datagen.flow(X_train, y_train, batch_size=128)

# Preprocess test/validation data for VGG
X_test_pre = preprocess_input(X_test)

# VGG16 model definition
base_model = VGG16(include_top=False, input_shape=(32,32,3), weights='imagenet')
x = base_model.output
x = Flatten()(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.5)(x)
predictions = Dense(10, activation='softmax')(x)
vgg_model = Model(inputs=base_model.input, outputs=predictions)

# Unfreeze last 4 layers for fine-tuning
for layer in base_model.layers[:-4]:
    layer.trainable = False
for layer in base_model.layers[-4:]:
    layer.trainable = True

vgg_model.compile(loss='categorical_crossentropy',
                  optimizer=Adam(learning_rate=1e-4),
                  metrics=['accuracy'])

callbacks = [
    EarlyStopping(patience=5, restore_best_weights=True),
    ReduceLROnPlateau(patience=3, factor=0.5, min_lr=1e-6)
]

# Train VGG16
vgg_hist = vgg_model.fit(
    train_flow,
    epochs=30,
    validation_data=(X_test_pre, y_test),
    callbacks=callbacks,
    steps_per_epoch=len(X_train)//128,
    verbose=2
)

# Plot learning curve
def learning_curve(hist):
    import matplotlib.pyplot as plt
    plt.figure(figsize=(12,4))
    plt.subplot(1,2,1)
    plt.plot(hist.history['loss'], label='Train Loss')
    plt.plot(hist.history['val_loss'], label='Val Loss')
    plt.title('Loss')
    plt.legend()
    plt.subplot(1,2,2)
    plt.plot(hist.history['accuracy'], label='Train Acc')
    plt.plot(hist.history['val_accuracy'], label='Val Acc')
    plt.title('Accuracy')
    plt.legend()
    plt.show()

learning_curve(vgg_hist)

# Evaluate on test set
vgg_model.evaluate(X_test_pre, y_test, batch_size=256, verbose=1)



# Second pre-trained model
from tensorflow.keras.applications.resnet50 import ResNet50
from keras.layers import GlobalAveragePooling2D

# Load and encode CIFAR-10
(X_train, y_train), (X_test, y_test) = cifar10.load_data()
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)
# DO NOT normalize X_train or X_test to float or [0,1].

# Augmentation and ResNet preprocessing for training data
datagen = ImageDataGenerator(
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    preprocessing_function=preprocess_input
)
datagen.fit(X_train)
train_flow = datagen.flow(X_train, y_train, batch_size=128)

# Preprocess test/validation data for ResNet
X_test_pre = preprocess_input(X_test)

# Build ResNet50 model for CIFAR-10
base_model = ResNet50(include_top=False, input_shape=(32,32,3), weights='imagenet')
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.5)(x)
predictions = Dense(10, activation='softmax')(x)
resnet_model = Model(inputs=base_model.input, outputs=predictions)

# Unfreeze last 10 layers for fine-tuning
for layer in base_model.layers[:-10]:
    layer.trainable = False
for layer in base_model.layers[-10:]:
    layer.trainable = True

resnet_model.compile(loss='categorical_crossentropy',
                     optimizer=Adam(learning_rate=1e-4),
                     metrics=['accuracy'])

callbacks = [
    EarlyStopping(patience=5, restore_best_weights=True),
    ReduceLROnPlateau(patience=3, factor=0.5, min_lr=1e-6)
]

# Train ResNet50
resnet_hist = resnet_model.fit(
    train_flow,
    epochs=30,
    validation_data=(X_test_pre, y_test),
    callbacks=callbacks,
    steps_per_epoch=len(X_train)//128,
    verbose=2
)

# Plot learning curves
def learning_curve(hist):
    import matplotlib.pyplot as plt
    plt.figure(figsize=(12,4))
    plt.subplot(1,2,1)
    plt.plot(hist.history['loss'], label='Train Loss')
    plt.plot(hist.history['val_loss'], label='Val Loss')
    plt.title('Loss')
    plt.legend()
    plt.subplot(1,2,2)
    plt.plot(hist.history['accuracy'], label='Train Acc')
    plt.plot(hist.history['val_accuracy'], label='Val Acc')
    plt.title('Accuracy')
    plt.legend()
    plt.show()

learning_curve(resnet_hist)

# Evaluate on test set
resnet_model.evaluate(X_test_pre, y_test, batch_size=256, verbose=1)

learning_curve(resnet_hist)

# Summary

"""#Conclusion


The assignment required building and evaluating CNNs on MNIST and CIFAR-10, then applying transfer learning using VGG16 and ResNet50. The biggest challenge was ensuring correct preprocessing for pre-trained networks, as manual normalization produced extremely poor results (~10% accuracy, i.e., random guessing). Once the pipeline was fixed, data was correctly passed to preprocess_input, and last layers were unfrozen for adaptation, both VGG16 and ResNet50 performed much better. Regularization (dropout), advanced optimizers, and callbacks further boosted performance and generalization.

Key changes to improve VGG and ResNet results:

Used model-specific preprocess_input rather than generic normalization.

Ensured augmentation and validation processing matched each architecture’s requirements.

Unfroze final layers for meaningful transfer learning.

Added learning rate schedules and early stopping.

Verified one-hot encoding and no double-preprocessing of inputs.

Through these changes, you raised accuracy from near-random to substantially better, demonstrating the importance of correct input pipelines and fine-tuning in deep learning with pre-trained architectures

.

.

.

.

.

.

.

.

.
"""

# End Of Doc