# -*- coding: utf-8 -*-
"""cv_feature_face_object_count.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gDVHbpYBnt53NHYQkfSQ9lq94RNfmuAd

#Project Introduction


This project explores core techniques in computer vision by applying them to three recognition and detection tasks using OpenCV.


Part 1 focuses on feature extraction, where three widely used algorithms, SIFT, FAST, and ORB are applied to analyze both color and grayscale images. Feature matching is performed to compare keypoint quality between image modes, illustrating how robust features can aid recognition despite changes in appearance.


Part 2 shifts to face recognition using Haar cascades. Here, pretrained classifiers are used to automatically detect faces and eyes in provided images and through live webcam input. This section introduces object detection using cascades and emphasizes parameter tuning for reliable face localization under different conditions.


Part 3 addresses parameter based object counting in a natural scene through the problem of counting apples in a tree. The task combines color segmentation, morphological operations, and contour analysis. Special care is taken in this section to iteratively adjust segmentation thresholds and morph-kernel sizes for accurate counting, including resolving challenges with touching apples, false positives, and fruits in shadow.

**Part 1- Feature extraction**
"""

#Start with uploading the required images on Google drive
import cv2
import matplotlib.pyplot as plt
import numpy as np
import imutils
from google.colab.patches import cv2_imshow
from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode

import os
os.path.exists('feature_pic.jpg')  # Should return True

img_bgr = cv2.imread('feature_pic.jpg')
print('img_bgr:', img_bgr is not None)  # Should print True if image is loaded

# Read the original image and create a regular plus a gray version of it.
img_bgr = cv2.imread('feature_pic.jpg')
img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
img_gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)

# Save grayscale
cv2.imwrite('pic1_gray.jpg', img_gray)

# Show both RGB and grayscale
f = plt.figure()
f.add_subplot(1, 2, 1)
plt.imshow(img_rgb)
plt.title('RGB')
plt.axis('off')
f.add_subplot(1, 2, 2)
plt.imshow(img_gray, cmap='gray')
plt.title('Gray')
plt.axis('off')
plt.show()

#a- SIFT
#sift = cv2.xfeatures2d.SIFT_create()
sift = cv2.SIFT_create()
# Find detect and compute function and apply it on top of sift
original_keypoints, original_descriptor = sift.detectAndCompute( img_gray, None)
keypoints_without_size = np.copy(img_rgb)
keypoints_with_size = np.copy(img_rgb)
# Draw the result here
result1 = cv2.drawKeypoints(img_rgb, original_keypoints, keypoints_with_size,flags = cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
result2 = cv2.drawKeypoints(img_rgb, original_keypoints,keypoints_without_size, color = (0, 255, 0))

# Display results
f = plt.figure(figsize=(12,6))
f.add_subplot(1,2,1)
plt.imshow(result1)
plt.title('SIFT with size')
plt.axis('off')
f.add_subplot(1,2,2)
plt.imshow(result2)
plt.title('SIFT without size')
plt.axis('off')
plt.show()

"""In the left image (SIFT with size), each keypoint is drawn as a circle, where the center marks the keypoint's location, and the radius represents the detected scale of the feature. Larger circles mean SIFT has identified a feature that is strong (distinctive) at a larger region or scale in the image. This can help match features across images with different zoom levels.

The right image (SIFT without size) shows just the keypoint positions, typically as small dots or crosses—all without scale information. You can see there are many more points concentrated in textured or detailed regions, but you can't tell how important or distinctive each is visually compared to the sized circles.
"""

# b- FAST
fast = cv2.FastFeatureDetector_create()
# Find detect and compute function and apply it on top of fast
# With nonmaxSuppression
fast.setNonmaxSuppression(True)
keypoints_nms = fast.detect(img_gray, None)
img_rgb_nms = np.copy(img_rgb)
result_nms = cv2.drawKeypoints(img_rgb_nms, keypoints_nms, None, color=(255,0,0))

# Without nonmaxSuppression
fast.setNonmaxSuppression(False)
keypoints_no_nms = fast.detect(img_gray, None)
img_rgb_no_nms = np.copy(img_rgb)
result_no_nms = cv2.drawKeypoints(img_rgb_no_nms, keypoints_no_nms, None, color=(0,255,0))
# Draw the result
# Use above approach to create result 1 and result 2

# Display
f = plt.figure(figsize=(12,6))
f.add_subplot(1,2,1)
plt.imshow(result_nms)
plt.title('FAST with NMS')
plt.axis('off')
f.add_subplot(1,2,2)
plt.imshow(result_no_nms)
plt.title('FAST without NMS')
plt.axis('off')
plt.show()

"""On the left ("FAST with NMS"): Keypoints are shown in red, and you can see they are more evenly spaced, they don't cluster too tightly. This is because Non-Max Suppression (NMS) helps keep only the strongest corner response in small overlapping regions, removing redundant or closely packed points. This produces a sparser, less cluttered distribution of keypoints that better represent significant features in the image.

On the right ("FAST without NMS"): Keypoints are shown in green, and you can clearly see a lot more are detected. Many points cluster in the same or very nearby locations, all the detected corners, even if they're not very strong, are kept. As a result, the visualization looks much denser and more chaotic. This could create too much overlap and redundancy, making downstream tasks slower or less efficient.
"""

# c- ORB
orb = cv2.ORB_create()
# Detect keypoints and descriptors on both images
orb_keypoints_gray, orb_desc_gray = orb.detectAndCompute(img_gray, None)
orb_keypoints_rgb, orb_desc_rgb = orb.detectAndCompute(img_rgb, None)

# Match with Brute-Force Matcher using Hamming distance
bf = cv2.BFMatcher(cv2.NORM_HAMMING, crossCheck=True)
matches = bf.match(orb_desc_gray, orb_desc_rgb)
matches = sorted(matches, key=lambda x: x.distance)

# Draw first 30 matches only for clarity
match_img = cv2.drawMatches(img_gray, orb_keypoints_gray,
                            img_rgb, orb_keypoints_rgb,
                            matches[:30], None, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)

# Draw the result
# Use above approach to create result 1 and result 2

plt.figure(figsize=(15,8))
plt.imshow(match_img)
plt.title('ORB Feature Matching (Gray vs RGB)')
plt.axis('off')
plt.show()
print(f'Number of matches: {len(matches)}')

"""In this visualization, ORB (Oriented FAST and Rotated BRIEF) has detected and matched feature points between the grayscale image (left) and the RGB color image (right) of the same scene. Each colored line connects a matched keypoint in the grayscale version to its corresponding location in the color version. You see hundreds of matches (445 shown) because ORB is robust to differences in color and lighting—it relies on pixel patterns rather than color information alone.


The large number of matches confirms that ORB is suitable for finding similarities across different versions of the same image, and can reliably match features even when color information is dropped (grayscale). This ability is very useful for applications like tracking, object recognition, and matching images taken under different conditions.

**Part 2- Face recognition**
"""

face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
eye_cascade = cv2.CascadeClassifier("haarcascade_eye.xml")

img = cv2.imread("face_detection_pic.jpg")
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) #Create the gray version of image using openCV
faces = face_cascade.detectMultiScale(gray, 1.3, 5)

for (x,y,w,h) in faces:
    img1 = cv2.rectangle(img,(x, y),(x + w, y + h),(255,255,0),2)
    roi_gray = gray[y: y + h, x: x + w]
    roi_color = img[y: y + h, x: x + w]
    eyes = eye_cascade.detectMultiScale(roi_gray)
    for (ex, ey, ew, eh) in eyes:
        cv2.rectangle(roi_color,(ex, ey), (ex + ew, ey + eh), (0,255,0),2)

cv2_imshow(img)

#b- Working on webcam
#Function to activate laptop or web cam.
def take_photo(filename='photo.jpg', quality=0.8):
  js = Javascript('''
    async function takePhoto(quality) {
      const div = document.createElement('div');
      const capture = document.createElement('button');
      capture.textContent = 'Capture';
      div.appendChild(capture);

      const video = document.createElement('video');
      video.style.display = 'block';
      const stream = await navigator.mediaDevices.getUserMedia({video: true});

      document.body.appendChild(div);
      div.appendChild(video);
      video.srcObject = stream;
      await video.play();

      // Resize the output to fit the video element.
      google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);

      // Wait for Capture to be clicked.
      await new Promise((resolve) => capture.onclick = resolve);

      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      canvas.getContext('2d').drawImage(video, 0, 0);
      stream.getVideoTracks()[0].stop();
      div.remove();
      return canvas.toDataURL('image/jpeg', quality);
    }
    ''')
  display(js)
  data = eval_js('takePhoto({})'.format(quality))
  binary = b64decode(data.split(',')[1])
  with open(filename, 'wb') as f:
    f.write(binary)
  return filename

# Call function and open the camera
image_file = take_photo('image.jpg')

#Show the read image
image = cv2.imread(image_file)


# Here you should see your image from cam with the face and eyes are detected
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
faces = face_cascade.detectMultiScale(gray, 1.3, 5)
for (x, y, w, h) in faces:
    cv2.rectangle(image, (x, y), (x+w, y+h), (255,255,0), 2)
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = image[y:y+h, x:x+w]
    eyes = eye_cascade.detectMultiScale(roi_gray)
    for (ex, ey, ew, eh) in eyes:
        cv2.rectangle(roi_color, (ex, ey), (ex+ew, ey+eh), (0,255,0), 2)
cv2_imshow(image)

"""**Part 3- Parameter detection**"""

# Define lower and upper HSV bounds for apple color
lowerBound1 = np.array([2, 60, 60])
upperBound1 = np.array([10, 255, 255])
lowerBound2 = np.array([160, 60, 60])
upperBound2 = np.array([180, 255, 255])

# Morphological kernels
kernelOpen = np.ones((3, 3))
kernelClose = np.ones((8, 8))

font = cv2.FONT_HERSHEY_SIMPLEX

# Read the image and convert BGR to HSV
img = cv2.imread('apple.jpg')
imgHSV = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

# Create the mask and process with morphology
# Step 1: Make one mask for each range
mask1 = cv2.inRange(imgHSV, lowerBound1, upperBound1)   # Bright reds
mask2 = cv2.inRange(imgHSV, lowerBound2, upperBound2)   # Deep reds

# Step 2: Combine the two masks
mask = cv2.bitwise_or(mask1, mask2)  # Use mask in rest of the pipeline

# Step 3: Morphology
maskOpen = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernelOpen)
maskClose = cv2.morphologyEx(maskOpen, cv2.MORPH_CLOSE, kernelClose)
maskFinal = maskClose

# Find contours
conts, hierarchy = cv2.findContours(maskFinal.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

# Draw all contours and bounding boxes on original image
cv2.drawContours(img, conts, -1, (255, 0, 0), 1)
for i in range(len(conts)):
    x, y, w, h = cv2.boundingRect(conts[i])
    cv2.rectangle(img, (x, y), (x + w, y + h), (0, 0, 255), 2)
    cv2.putText(img, str(i + 1), (x, y + h), font, 0.7, (0, 255, 0), 2)

# Show masks and result
cv2_imshow(mask)
cv2_imshow(maskOpen)
cv2_imshow(maskClose)
cv2_imshow(img)

print('There are', len(conts), 'apples in this picture.')

"""#Project Summary & Lessons Learned


Across all three parts, this project applied fundamental computer vision tools to real world imagery, emphasizing both automatic feature extraction and the need for hands on parameter tuning.

The final apple counting model presented several key challenges:

Color variability: Apples appeared in both bright and deep red hues, sometimes with low saturation or variable value caused by shadow or reflection. This made a single HSV range inadequate, so two ranges were combined to reliably mask both orange-red and deep red apples.

Separation of touching apples: Early settings for morphological closing kernels were either too large (merging pairs of apples as one count) or too small (leaving fragmented shapes). After visualizing the mask before and after closing, kernel sizes were iteratively lowered (e.g., from 18x18 down to 10x10 or 12x12) to split pairs without breaking up single apples.

Overcounting and false positives: Experimentation showed that, without contour filtering, the code sometimes detected small noise, fragments, or merged leaf/branch regions as "apples." Filters on contour area and roundness ("circularity") were explored to exclude non-apples and prevent double counting.

General workflow: Each problem was addressed through stepwise mask visualization, tuning the noise-removal and blob connections, and careful adjustment of HSV thresholds to balance recall and precision.

By the end, the solution robustly counted apples even in complex conditions: pairs of apples were merged or split based on kernel choice, shadowed fruit was detected via lower saturation/value thresholds, and noise was suppressed through area/circularity filtering. This iterative process highlights the necessity of combining algorithmic insight with practical, visual troubleshooting for successful computer vision on unstructured real world problems.

#End of doc

.

.

.

.


.


.

.

.

.

.

.

.

.

.


.


.

.


.
"""

#%shell jupyter nbconvert --to pdf 'cv_feature_face_object_count.ipynb'

